// Code generated by internal/cmd/fitgen/main.go. DO NOT EDIT.

// Copyright 2023 The FIT SDK for Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package typedef

import (
	"strconv"
)

type EwbankGradingScale byte

const (
	EwbankGradingScale4       EwbankGradingScale = 0  // 4
	EwbankGradingScale5       EwbankGradingScale = 1  // 5
	EwbankGradingScale6       EwbankGradingScale = 2  // 6
	EwbankGradingScale7       EwbankGradingScale = 3  // 7
	EwbankGradingScale8       EwbankGradingScale = 4  // 8
	EwbankGradingScale9       EwbankGradingScale = 5  // 9
	EwbankGradingScale10      EwbankGradingScale = 6  // 10
	EwbankGradingScale11      EwbankGradingScale = 7  // 11
	EwbankGradingScale12      EwbankGradingScale = 8  // 12
	EwbankGradingScale13      EwbankGradingScale = 9  // 13
	EwbankGradingScale14      EwbankGradingScale = 10 // 14
	EwbankGradingScale15      EwbankGradingScale = 11 // 15
	EwbankGradingScale16      EwbankGradingScale = 12 // 16
	EwbankGradingScale17      EwbankGradingScale = 13 // 17
	EwbankGradingScale18      EwbankGradingScale = 14 // 18
	EwbankGradingScale19      EwbankGradingScale = 15 // 19
	EwbankGradingScale20      EwbankGradingScale = 16 // 20
	EwbankGradingScale21      EwbankGradingScale = 17 // 21
	EwbankGradingScale22      EwbankGradingScale = 18 // 22
	EwbankGradingScale23      EwbankGradingScale = 19 // 23
	EwbankGradingScale24      EwbankGradingScale = 20 // 24
	EwbankGradingScale25      EwbankGradingScale = 21 // 25
	EwbankGradingScale26      EwbankGradingScale = 22 // 26
	EwbankGradingScale27      EwbankGradingScale = 23 // 27
	EwbankGradingScale28      EwbankGradingScale = 24 // 28
	EwbankGradingScale29      EwbankGradingScale = 25 // 29
	EwbankGradingScale30      EwbankGradingScale = 26 // 30
	EwbankGradingScale31      EwbankGradingScale = 27 // 31
	EwbankGradingScale32      EwbankGradingScale = 28 // 32
	EwbankGradingScale33      EwbankGradingScale = 29 // 33
	EwbankGradingScale34      EwbankGradingScale = 30 // 34
	EwbankGradingScale35      EwbankGradingScale = 31 // 35
	EwbankGradingScale36      EwbankGradingScale = 32 // 36
	EwbankGradingScale37      EwbankGradingScale = 33 // 37
	EwbankGradingScale38      EwbankGradingScale = 34 // 38
	EwbankGradingScaleInvalid EwbankGradingScale = 0xFF
)

func (e EwbankGradingScale) Byte() byte { return byte(e) }

func (e EwbankGradingScale) String() string {
	switch e {
	case EwbankGradingScale4:
		return "4"
	case EwbankGradingScale5:
		return "5"
	case EwbankGradingScale6:
		return "6"
	case EwbankGradingScale7:
		return "7"
	case EwbankGradingScale8:
		return "8"
	case EwbankGradingScale9:
		return "9"
	case EwbankGradingScale10:
		return "10"
	case EwbankGradingScale11:
		return "11"
	case EwbankGradingScale12:
		return "12"
	case EwbankGradingScale13:
		return "13"
	case EwbankGradingScale14:
		return "14"
	case EwbankGradingScale15:
		return "15"
	case EwbankGradingScale16:
		return "16"
	case EwbankGradingScale17:
		return "17"
	case EwbankGradingScale18:
		return "18"
	case EwbankGradingScale19:
		return "19"
	case EwbankGradingScale20:
		return "20"
	case EwbankGradingScale21:
		return "21"
	case EwbankGradingScale22:
		return "22"
	case EwbankGradingScale23:
		return "23"
	case EwbankGradingScale24:
		return "24"
	case EwbankGradingScale25:
		return "25"
	case EwbankGradingScale26:
		return "26"
	case EwbankGradingScale27:
		return "27"
	case EwbankGradingScale28:
		return "28"
	case EwbankGradingScale29:
		return "29"
	case EwbankGradingScale30:
		return "30"
	case EwbankGradingScale31:
		return "31"
	case EwbankGradingScale32:
		return "32"
	case EwbankGradingScale33:
		return "33"
	case EwbankGradingScale34:
		return "34"
	case EwbankGradingScale35:
		return "35"
	case EwbankGradingScale36:
		return "36"
	case EwbankGradingScale37:
		return "37"
	case EwbankGradingScale38:
		return "38"
	default:
		return "EwbankGradingScaleInvalid(" + strconv.Itoa(int(e)) + ")"
	}
}

// FromString parse string into EwbankGradingScale constant it's represent, return EwbankGradingScaleInvalid if not found.
func EwbankGradingScaleFromString(s string) EwbankGradingScale {
	switch s {
	case "4":
		return EwbankGradingScale4
	case "5":
		return EwbankGradingScale5
	case "6":
		return EwbankGradingScale6
	case "7":
		return EwbankGradingScale7
	case "8":
		return EwbankGradingScale8
	case "9":
		return EwbankGradingScale9
	case "10":
		return EwbankGradingScale10
	case "11":
		return EwbankGradingScale11
	case "12":
		return EwbankGradingScale12
	case "13":
		return EwbankGradingScale13
	case "14":
		return EwbankGradingScale14
	case "15":
		return EwbankGradingScale15
	case "16":
		return EwbankGradingScale16
	case "17":
		return EwbankGradingScale17
	case "18":
		return EwbankGradingScale18
	case "19":
		return EwbankGradingScale19
	case "20":
		return EwbankGradingScale20
	case "21":
		return EwbankGradingScale21
	case "22":
		return EwbankGradingScale22
	case "23":
		return EwbankGradingScale23
	case "24":
		return EwbankGradingScale24
	case "25":
		return EwbankGradingScale25
	case "26":
		return EwbankGradingScale26
	case "27":
		return EwbankGradingScale27
	case "28":
		return EwbankGradingScale28
	case "29":
		return EwbankGradingScale29
	case "30":
		return EwbankGradingScale30
	case "31":
		return EwbankGradingScale31
	case "32":
		return EwbankGradingScale32
	case "33":
		return EwbankGradingScale33
	case "34":
		return EwbankGradingScale34
	case "35":
		return EwbankGradingScale35
	case "36":
		return EwbankGradingScale36
	case "37":
		return EwbankGradingScale37
	case "38":
		return EwbankGradingScale38
	default:
		return EwbankGradingScaleInvalid
	}
}

// List returns all constants.
func ListEwbankGradingScale() []EwbankGradingScale {
	return []EwbankGradingScale{
		EwbankGradingScale4,
		EwbankGradingScale5,
		EwbankGradingScale6,
		EwbankGradingScale7,
		EwbankGradingScale8,
		EwbankGradingScale9,
		EwbankGradingScale10,
		EwbankGradingScale11,
		EwbankGradingScale12,
		EwbankGradingScale13,
		EwbankGradingScale14,
		EwbankGradingScale15,
		EwbankGradingScale16,
		EwbankGradingScale17,
		EwbankGradingScale18,
		EwbankGradingScale19,
		EwbankGradingScale20,
		EwbankGradingScale21,
		EwbankGradingScale22,
		EwbankGradingScale23,
		EwbankGradingScale24,
		EwbankGradingScale25,
		EwbankGradingScale26,
		EwbankGradingScale27,
		EwbankGradingScale28,
		EwbankGradingScale29,
		EwbankGradingScale30,
		EwbankGradingScale31,
		EwbankGradingScale32,
		EwbankGradingScale33,
		EwbankGradingScale34,
		EwbankGradingScale35,
		EwbankGradingScale36,
		EwbankGradingScale37,
		EwbankGradingScale38,
	}
}
