// Code generated by internal/cmd/fitgen/main.go. DO NOT EDIT.

// Copyright 2023 The Fit SDK for Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mesgdef

import (
	"github.com/muktihari/fit/kit/datetime"
	"github.com/muktihari/fit/kit/typeconv"
	"github.com/muktihari/fit/profile/basetype"
	"github.com/muktihari/fit/profile/typedef"
	"github.com/muktihari/fit/proto"
	"time"
)

// HsaBodyBatteryData is a HsaBodyBatteryData message.
type HsaBodyBatteryData struct {
	Timestamp          time.Time // Units: s
	Level              []int8    // Array: [N]; Units: percent; Body battery level
	Charged            []int16   // Array: [N]; Body battery charged value
	Uncharged          []int16   // Array: [N]; Body battery uncharged value
	ProcessingInterval uint16    // Units: s; Processing interval length in seconds

	// Developer Fields are dynamic, can't be mapped as struct's fields.
	// [Added since protocol version 2.0]
	DeveloperFields []proto.DeveloperField
}

// NewHsaBodyBatteryData creates new HsaBodyBatteryData struct based on given mesg.
// If mesg is nil, it will return HsaBodyBatteryData with all fields being set to its corresponding invalid value.
func NewHsaBodyBatteryData(mesg *proto.Message) *HsaBodyBatteryData {
	vals := [254]any{}

	var developerFields []proto.DeveloperField
	if mesg != nil {
		for i := range mesg.Fields {
			if mesg.Fields[i].Num >= byte(len(vals)) {
				continue
			}
			vals[mesg.Fields[i].Num] = mesg.Fields[i].Value
		}
		developerFields = mesg.DeveloperFields
	}

	return &HsaBodyBatteryData{
		Timestamp:          datetime.ToTime(vals[253]),
		Level:              typeconv.ToSliceSint8[int8](vals[1]),
		Charged:            typeconv.ToSliceSint16[int16](vals[2]),
		Uncharged:          typeconv.ToSliceSint16[int16](vals[3]),
		ProcessingInterval: typeconv.ToUint16[uint16](vals[0]),

		DeveloperFields: developerFields,
	}
}

// ToMesg converts HsaBodyBatteryData into proto.Message.
func (m *HsaBodyBatteryData) ToMesg(fac Factory) proto.Message {
	fieldsArray := fieldsPool.Get().(*[256]proto.Field)
	defer fieldsPool.Put(fieldsArray)

	fields := (*fieldsArray)[:0] // Create slice from array with zero len.
	mesg := fac.CreateMesgOnly(typedef.MesgNumHsaBodyBatteryData)

	if datetime.ToUint32(m.Timestamp) != basetype.Uint32Invalid {
		field := fac.CreateField(mesg.Num, 253)
		field.Value = datetime.ToUint32(m.Timestamp)
		fields = append(fields, field)
	}
	if m.Level != nil {
		field := fac.CreateField(mesg.Num, 1)
		field.Value = m.Level
		fields = append(fields, field)
	}
	if m.Charged != nil {
		field := fac.CreateField(mesg.Num, 2)
		field.Value = m.Charged
		fields = append(fields, field)
	}
	if m.Uncharged != nil {
		field := fac.CreateField(mesg.Num, 3)
		field.Value = m.Uncharged
		fields = append(fields, field)
	}
	if m.ProcessingInterval != basetype.Uint16Invalid {
		field := fac.CreateField(mesg.Num, 0)
		field.Value = m.ProcessingInterval
		fields = append(fields, field)
	}

	mesg.Fields = make([]proto.Field, len(fields))
	copy(mesg.Fields, fields)

	mesg.DeveloperFields = m.DeveloperFields

	return mesg
}

// SetTimestamp sets HsaBodyBatteryData value.
//
// Units: s
func (m *HsaBodyBatteryData) SetTimestamp(v time.Time) *HsaBodyBatteryData {
	m.Timestamp = v
	return m
}

// SetLevel sets HsaBodyBatteryData value.
//
// Array: [N]; Units: percent; Body battery level
func (m *HsaBodyBatteryData) SetLevel(v []int8) *HsaBodyBatteryData {
	m.Level = v
	return m
}

// SetCharged sets HsaBodyBatteryData value.
//
// Array: [N]; Body battery charged value
func (m *HsaBodyBatteryData) SetCharged(v []int16) *HsaBodyBatteryData {
	m.Charged = v
	return m
}

// SetUncharged sets HsaBodyBatteryData value.
//
// Array: [N]; Body battery uncharged value
func (m *HsaBodyBatteryData) SetUncharged(v []int16) *HsaBodyBatteryData {
	m.Uncharged = v
	return m
}

// SetProcessingInterval sets HsaBodyBatteryData value.
//
// Units: s; Processing interval length in seconds
func (m *HsaBodyBatteryData) SetProcessingInterval(v uint16) *HsaBodyBatteryData {
	m.ProcessingInterval = v
	return m
}

// SetDeveloperFields HsaBodyBatteryData's DeveloperFields.
func (m *HsaBodyBatteryData) SetDeveloperFields(developerFields ...proto.DeveloperField) *HsaBodyBatteryData {
	m.DeveloperFields = developerFields
	return m
}
