// Code generated by internal/cmd/fitgen/main.go. DO NOT EDIT.
// SDK Version: 21.126

// Copyright 2023 The Fit SDK for Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mesgdef

import (
	"github.com/muktihari/fit/kit/datetime"
	"github.com/muktihari/fit/kit/typeconv"
	"github.com/muktihari/fit/profile/basetype"
	"github.com/muktihari/fit/profile/typedef"
	"github.com/muktihari/fit/proto"
	"time"
)

// StressLevel is a StressLevel message.
type StressLevel struct {
	StressLevelValue int16
	StressLevelTime  time.Time // Units: s; Time stress score was calculated

	// Developer Fields are dynamic, can't be mapped as struct's fields.
	// [Added since protocol version 2.0]
	DeveloperFields []proto.DeveloperField
}

// NewStressLevel creates new StressLevel struct based on given mesg.
// If mesg is nil, it will return StressLevel with all fields being set to its corresponding invalid value.
func NewStressLevel(mesg *proto.Message) *StressLevel {
	vals := [2]any{}

	var developerFields []proto.DeveloperField
	if mesg != nil {
		for i := range mesg.Fields {
			if mesg.Fields[i].Num >= byte(len(vals)) {
				continue
			}
			vals[mesg.Fields[i].Num] = mesg.Fields[i].Value
		}
		developerFields = mesg.DeveloperFields
	}

	return &StressLevel{
		StressLevelValue: typeconv.ToSint16[int16](vals[0]),
		StressLevelTime:  datetime.ToTime(vals[1]),

		DeveloperFields: developerFields,
	}
}

// ToMesg converts StressLevel into proto.Message.
func (m *StressLevel) ToMesg(fac Factory) proto.Message {
	fieldsPtr := fieldsPool.Get().(*[256]proto.Field)
	defer fieldsPool.Put(fieldsPtr)

	fields := (*fieldsPtr)[:0] // Create slice from array with zero len.
	mesg := fac.CreateMesgOnly(typedef.MesgNumStressLevel)

	if m.StressLevelValue != basetype.Sint16Invalid {
		field := fac.CreateField(mesg.Num, 0)
		field.Value = m.StressLevelValue
		fields = append(fields, field)
	}
	if datetime.ToUint32(m.StressLevelTime) != basetype.Uint32Invalid {
		field := fac.CreateField(mesg.Num, 1)
		field.Value = datetime.ToUint32(m.StressLevelTime)
		fields = append(fields, field)
	}

	mesg.Fields = make([]proto.Field, len(fields))
	copy(mesg.Fields, fields)

	mesg.DeveloperFields = m.DeveloperFields

	return mesg
}

// SetStressLevelValue sets StressLevel value.
func (m *StressLevel) SetStressLevelValue(v int16) *StressLevel {
	m.StressLevelValue = v
	return m
}

// SetStressLevelTime sets StressLevel value.
//
// Units: s; Time stress score was calculated
func (m *StressLevel) SetStressLevelTime(v time.Time) *StressLevel {
	m.StressLevelTime = v
	return m
}

// SetDeveloperFields StressLevel's DeveloperFields.
func (m *StressLevel) SetDeveloperFields(developerFields ...proto.DeveloperField) *StressLevel {
	m.DeveloperFields = developerFields
	return m
}
