// Code generated by internal/cmd/fitgen/main.go. DO NOT EDIT.
// SDK Version: 21.126

// Copyright 2023 The Fit SDK for Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mesgdef

import (
	"github.com/muktihari/fit/kit/typeconv"
	"github.com/muktihari/fit/profile/basetype"
	"github.com/muktihari/fit/profile/typedef"
	"github.com/muktihari/fit/proto"
)

// WatchfaceSettings is a WatchfaceSettings message.
type WatchfaceSettings struct {
	MessageIndex typedef.MessageIndex
	Mode         typedef.WatchfaceMode
	Layout       byte

	// Developer Fields are dynamic, can't be mapped as struct's fields.
	// [Added since protocol version 2.0]
	DeveloperFields []proto.DeveloperField
}

// NewWatchfaceSettings creates new WatchfaceSettings struct based on given mesg.
// If mesg is nil, it will return WatchfaceSettings with all fields being set to its corresponding invalid value.
func NewWatchfaceSettings(mesg *proto.Message) *WatchfaceSettings {
	vals := [255]any{}

	var developerFields []proto.DeveloperField
	if mesg != nil {
		for i := range mesg.Fields {
			if mesg.Fields[i].Num >= byte(len(vals)) {
				continue
			}
			vals[mesg.Fields[i].Num] = mesg.Fields[i].Value
		}
		developerFields = mesg.DeveloperFields
	}

	return &WatchfaceSettings{
		MessageIndex: typeconv.ToUint16[typedef.MessageIndex](vals[254]),
		Mode:         typeconv.ToEnum[typedef.WatchfaceMode](vals[0]),
		Layout:       typeconv.ToByte[byte](vals[1]),

		DeveloperFields: developerFields,
	}
}

// ToMesg converts WatchfaceSettings into proto.Message.
func (m *WatchfaceSettings) ToMesg(fac Factory) proto.Message {
	mesg := fac.CreateMesgOnly(typedef.MesgNumWatchfaceSettings)
	mesg.Fields = make([]proto.Field, 0, m.size())

	if typeconv.ToUint16[uint16](m.MessageIndex) != basetype.Uint16Invalid {
		field := fac.CreateField(mesg.Num, 254)
		field.Value = typeconv.ToUint16[uint16](m.MessageIndex)
		mesg.Fields = append(mesg.Fields, field)
	}
	if typeconv.ToEnum[byte](m.Mode) != basetype.EnumInvalid {
		field := fac.CreateField(mesg.Num, 0)
		field.Value = typeconv.ToEnum[byte](m.Mode)
		mesg.Fields = append(mesg.Fields, field)
	}
	if m.Layout != basetype.ByteInvalid {
		field := fac.CreateField(mesg.Num, 1)
		field.Value = m.Layout
		mesg.Fields = append(mesg.Fields, field)
	}

	mesg.DeveloperFields = m.DeveloperFields

	return mesg
}

// size returns size of WatchfaceSettings's valid fields.
func (m *WatchfaceSettings) size() byte {
	var size byte
	if typeconv.ToUint16[uint16](m.MessageIndex) != basetype.Uint16Invalid {
		size++
	}
	if typeconv.ToEnum[byte](m.Mode) != basetype.EnumInvalid {
		size++
	}
	if m.Layout != basetype.ByteInvalid {
		size++
	}
	return size
}

// SetMessageIndex sets WatchfaceSettings value.
func (m *WatchfaceSettings) SetMessageIndex(v typedef.MessageIndex) *WatchfaceSettings {
	m.MessageIndex = v
	return m
}

// SetMode sets WatchfaceSettings value.
func (m *WatchfaceSettings) SetMode(v typedef.WatchfaceMode) *WatchfaceSettings {
	m.Mode = v
	return m
}

// SetLayout sets WatchfaceSettings value.
func (m *WatchfaceSettings) SetLayout(v byte) *WatchfaceSettings {
	m.Layout = v
	return m
}

// SetDeveloperFields WatchfaceSettings's DeveloperFields.
func (m *WatchfaceSettings) SetDeveloperFields(developerFields ...proto.DeveloperField) *WatchfaceSettings {
	m.DeveloperFields = developerFields
	return m
}
